# Generated by Django 2.1.4 on 2018-12-30 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Reading',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temp', models.IntegerField()),
                ('wspeed', models.CharField(max_length=20)),
                ('visible', models.CharField(max_length=20)),
                ('icon_url', models.URLField()),
                ('humid', models.CharField(max_length=50)),
            ],
        ),
    ]
